### ISSUE TITLE
Error: Adding speaker on Win 11

### ISSUE THREAD

**Issue by tin2tin** [WhisperSpeech/WhisperSpeech#72]
Trying to add speaker to the test file throws an error on Windows 11.

```
from whisperspeech.pipeline import Pipeline

pipe = Pipeline(s2a_ref='collabora/whisperspeech:s2a-q4-small-en+pl.model')
# pipe = Pipeline(s2a_ref='collabora/whisperspeech:s2a-q4-tiny-en+pl.model')
# pipe = Pipeline(s2a_ref='collabora/whisperspeech:s2a-q4-base-en+pl.model')

audio_tensor = pipe.generate("""
 This is some sample text.  You would add text here that you want spoken and then only leave one of the above lines ununcommented for the model you want to test.  Note that this script does not rely on the standard method within the whisperspeech pipeline.  Rather, it replaces a part of the functionality with reliance on pydub instead.  This approach "just worked."  Feel free to modify or distribute at your pleasure.
""", speaker='https://upload.wikimedia.org/wikipedia/commons/7/75/Winston_Churchill_-_Be_Ye_Men_of_Valour.ogg', lang='en', cps=14)

# generate uses CUDA if available; therefore, it's necessary to move to CPU before converting to NumPy array
audio_np = (audio_tensor.cpu().numpy() * 32767).astype(np.int16)

if len(audio_np.shape) == 1:
    audio_np = np.expand_dims(audio_np, axis=0)
else:
    audio_np = audio_np.T

print("Array shape:", audio_np.shape)
print("Array dtype:", audio_np.dtype)

try:
    audio_segment = AudioSegment(
        audio_np.tobytes(), 
        frame_rate=24000, 
        sample_width=2, 
        channels=1
    )
    audio_segment.export('output_audio.wav', format='wav')
    print("Audio file generated: output_audio.wav")
except Exception as e:
    print(f"Error writing audio file: {e}")
```

And this is the error:

```
Traceback (most recent call last):
  File "...untitled_37.blend\Text.001", line 9, in <module>
  File "...\python\Lib\site-packages\whisperspeech\pipeline.py", line 87, in generate
    return self.vocoder.decode(self.generate_atoks(text, speaker, lang=lang, cps=cps, step_callback=step_callback))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\whisperspeech\pipeline.py", line 80, in generate_atoks
    elif isinstance(speaker, (str, Path)): speaker = self.extract_spk_emb(speaker)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\whisperspeech\pipeline.py", line 73, in extract_spk_emb
    samples, sr = torchaudio.load(fname)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\torchaudio\_backend\utils.py", line 205, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\torchaudio\_backend\soundfile.py", line 27, in load
    return soundfile_backend.load(uri, frame_offset, num_frames, normalize, channels_first, format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 221, in load
    with soundfile.SoundFile(filepath, "r") as file_:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\soundfile.py", line 1264, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "...\python\Lib\site-packages\soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'https://upload.wikimedia.org/wikipedia/commons/7/75/Winston_Churchill_-_Be_Ye_Men_of_Valour.ogg': System error.
Error: Python: Traceback (most recent call last):
  File "...untitled_37.blend\Text.001", line 9, in <module>
  File "...\python\Lib\site-packages\whisperspeech\pipeline.py", line 87, in generate
    return self.vocoder.decode(self.generate_atoks(text, speaker, lang=lang, cps=cps, step_callback=step_callback))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\whisperspeech\pipeline.py", line 80, in generate_atoks
    elif isinstance(speaker, (str, Path)): speaker = self.extract_spk_emb(speaker)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\whisperspeech\pipeline.py", line 73, in extract_spk_emb
    samples, sr = torchaudio.load(fname)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\torchaudio\_backend\utils.py", line 205, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\torchaudio\_backend\soundfile.py", line 27, in load
    return soundfile_backend.load(uri, frame_offset, num_frames, normalize, channels_first, format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 221, in load
    with soundfile.SoundFile(filepath, "r") as file_:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\soundfile.py", line 740, in __init__
    self._file = self._open(file, mode_int, closefd)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\python\Lib\site-packages\soundfile.py", line 1264, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "...\python\Lib\site-packages\soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'https://upload.wikimedia.org/wikipedia/commons/7/75/Winston_Churchill_-_Be_Ye_Men_of_Valour.ogg': System error.

```

**Comment by tin2tin** [comment]
Is it the .ogg format it can't read?

**Comment by BBC-Esq** [comment]
Same type of error that I received on windows 10 if I recall.

**Comment by tin2tin** [comment]
If I change it to a wav file, it works but that wall of messages is still there.

**Comment by BBC-Esq** [comment]
@zoq and @jpc , am I correct in understanding that if a user specifies the "speaker" parameter that this is the function that's supposed to run:
```

    def extract_spk_emb(self, fname):
        """Extracts a speaker embedding from the first 30 seconds of the give audio file.
        """
        import torchaudio
        if self.encoder is None:
            from speechbrain.pretrained import EncoderClassifier
            self.encoder = EncoderClassifier.from_hparams("speechbrain/spkrec-ecapa-voxceleb",
                                                          savedir="~/.cache/speechbrain/",
                                                          run_opts={"device": "cuda"})
        samples, sr = torchaudio.load(fname)
        samples = self.encoder.audio_normalizer(samples[0,:30*sr], sr)
        spk_emb = self.encoder.encode_batch(samples)
        return spk_emb[0,0]
```

...and that the result basically supersedes this portion that is otherwise the default:
```
    default_speaker = torch.tensor(
       [-0.2929, -0.4503,  0.4155, -0.1417,  0.0473, -0.1624, -0.2322,  0.7071,
         0.4800,  0.5496,  0.0410,  0.6236,  0.4729,  0.0587,  0.2194, -0.0466,
        -0.3036,  0.0497,  0.5028, -0.1703,  0.5039, -0.6464,  0.3857, -0.7350,
        -0.1605,  0.4808,  0.5397, -0.4851,  0.1774, -0.8712,  0.5789,  0.1785,
        -0.1417,  0.3039,  0.4232, -0.0186,  0.2685,  0.6153, -0.3103, -0.5706,
        -0.4494,  0.3394, -0.6184, -0.3617,  1.1041, -0.1178, -0.1885,  0.1997,
         0.5571, -0.2906, -0.0477, -0.4048, -0.1062,  1.4779,  0.1639, -0.3712,
        -0.1776, -0.0568, -0.6162,  0.0110, -0.0207, -0.1319, -0.3854,  0.7248,
         0.0343,  0.5724,  0.0670,  0.0486, -0.3813,  0.1738,  0.3017,  1.0502,
         0.1550,  0.5708,  0.0366,  0.5093,  0.0294, -0.7091, -0.8220, -0.1583,
        -0.2343,  0.1366,  0.7372, -0.0631,  0.1505,  0.4600, -0.1252, -0.5245,
         0.7523, -0.0386, -0.2587,  1.0066, -0.2037,  0.1617, -0.3800,  0.2790,
         0.0184, -0.5111, -0.7291,  0.1627,  0.2367, -0.0192,  0.4822, -0.4458,
         0.1457, -0.5884,  0.1909,  0.2563, -0.2035, -0.0377,  0.7771,  0.2139,
         0.3801,  0.6047, -0.6043, -0.2563, -0.0726,  0.3856,  0.3217,  0.0823,
        -0.1302,  0.3287,  0.5693,  0.2453,  0.8231,  0.0072,  1.0327,  0.6065,
        -0.0620, -0.5572,  0.5220,  0.2485,  0.1520,  0.0222, -0.2179, -0.7392,
        -0.3855,  0.1822,  0.1042,  0.7133,  0.3583,  0.0606, -0.0424, -0.9189,
        -0.4882, -0.5480, -0.5719, -0.1660, -0.3439, -0.5814, -0.2542,  0.0197,
         0.4942,  0.0915, -0.0420, -0.0035,  0.5578,  0.1051, -0.0891,  0.2348,
         0.6876, -0.6685,  0.8215, -0.3692, -0.3150, -0.0462, -0.6806, -0.2661,
        -0.0308, -0.0050,  0.6756, -0.1647,  1.0734,  0.0049,  0.4969,  0.0259,
        -0.8949,  0.0731,  0.0886,  0.3442, -0.1433, -0.6804,  0.2204,  0.1859,
         0.2702,  0.1699, -0.1443, -0.9614,  0.3261,  0.1718,  0.3545, -0.0686]
    )
```

Before I possibly tackle troubleshooting I'd like to know if I understand the basic flow of the scripts.  Thanks.

**Comment by BBC-Esq** [comment]
> If I change it to a wav file, it works but that wall of messages is still there.

Have you verified that the ultimate audio file does in fact sound like the speaker that you tried to specify?

**Comment by tin2tin** [comment]
Yes, it does work. Here is first Orson Wells and then Werner Herzog:

https://github.com/collabora/WhisperSpeech/assets/1322593/d8071faa-244f-4a16-8031-059162b2b2c6

**Comment by BBC-Esq** [comment]
Cool, can you please post the script you used again?  I still didn't get it working for some strange reason.

**Comment by tin2tin** [comment]
```
from whisperspeech.pipeline import Pipeline

pipe = Pipeline(s2a_ref='collabora/whisperspeech:s2a-q4-small-en+pl.model')
pipe.generate_to_file(filename, prompt, speaker="path to local wav file", lang='en', cps=14)
```

**Comment by jpc** [comment]
I have no opinion on any particular library for sound files but I think:
1. We want this to work out of the box on Windows and Linux/Mac
2. We probably want to support loading arbitrary mp3/ogg file for the reference speech
3. Loading directly from URLs is also nice for example code, maybe we can implement a simple wrapper ourselves on top of `requests` if `torchaudio` is not reliable on other platforms?
4. It would be nice to have one single dependency for loading and saving files for inference (training can use a lot more stuff since it does not put a burden on every user)

Do we all agree that this would be a good list of requirements?

**Comment by BBC-Esq** [comment]
> I have no opinion on any particular library for sound files but I think:
> 
>     1. We want this to work out of the box on Windows and Linux/Mac
> 
>     2. We probably want to support loading arbitrary mp3/ogg file for the reference speech
> 
>     3. Loading directly from URLs is also nice for example code, maybe we can implement a simple wrapper ourselves on top of `requests` if `torchaudio` is not reliable on other platforms?
> 
>     4. It would be nice to have one single dependency for loading and saving files for inference (training can use a lot more stuff since it does not put a burden on every user)
> 
> 
> Do we all agree that this would be a good list of requirements?

My only thoughts are regarding #3...

I originally was the one getting errors when using torchaudio on Windows that I think is the impetus for your message about possibly switching out torchaudio.  To bring you up to speed...eventually I WAS able to resolve the torchaudio-related error we discussed.  This required using ```pip install sounddevice```.  It's my understanding that torchaudio uses either sounddevice or "iosox" (not sure how to spell) under the hood...and for some reason I had to pip install sounddevice.

This fully resolved the error regarding torchaudio.  Thus, as long as it's clear that windows users (and possibly other platforms, I don't know?) might have to specifically install sounddevice, we shouldn't need to abandon torchaudio....that is, unless other users encounter different problems.

Overall, I was NOT able to get a good tensor of a speaker's voice despite using very high quality audio, and I haven't re-tried since then.  However, that's a separate issue and might involve my code...but as far as torchaudio and windows compatibility, hope this clarifies.

**Comment by jpc** [comment]
Hey, thanks for explaining this. So it would look like we should check if we can add `soundfile` to our dependencies to make sure it gets installed on Windows.

**Comment by BBC-Esq** [comment]
I would recommend adding it for Linux and Macos users as well.  Apparently @signalprime encountered an error stating that torchaudio backend wasn't available, which was solved by pip installing soundfile.  I believe his pull request might already do this?

**Comment by BBC-Esq** [comment]
Finally found the website for sox...apparently it hasn't been updated since 2015 so I'm not sure why in the world Pytorch would use it.  I say set the default to SoundDevice... :-)

https://sourceforge.net/projects/sox/files/sox/

**Comment by jpc** [comment]
Hey, nice job finding all that info. I was not aware of the history behind the torchaudio backends!

I agree with your conclusion - I’ll test a fresh Linux install and if you can confirm that torchaudio with soundfile works well on Windows then we can use this exclusively.

I also implemented a workaround to support downloading the file from a URL, even without Sox.

**Comment by BBC-Esq** [comment]
Should be resolved because soundfile was added.  Closing for now but feel free to post again if a similar issue exists.
